### ISSUE TITLE
Sync/Migrate doesn't work in 1.7

### ISSUE THREAD

**Issue by petedrennan** [chawk/django-easy-avatar#1]
I tried a simple install, but migrations don't seem to work in Django 1.7. I try to makemigrations and migrate, but nothing is detected. Any ideas why this might be?

**Comment by chawk** [comment]
sorry I have not had a moment to check this on Django 1.7, but after I installed in my recent project I didn't have any problems running migrations.  I'm assuming you had the django_easy_avatar listed in the installed apps?
